In [4]:
import pandas
import numpy

In [5]:
mabc = pandas.read_csv('data/monthly_arrivals_by_country_filtered.csv')

In [6]:
fsi = pandas.read_csv("data/fragilestatesindex_joined.csv")

In [7]:
PSQ_TMS = pandas.read_csv("data/PSQ_TMS.csv", skiprows=range(5), na_values="*")

In [8]:
test = PSQ_TMS[PSQ_TMS["Country Name"] == "Afghanistan"]

In [9]:
test.drop(["Origin / Returned from", "Population type"], axis=1,
    inplace=True)

/Users/steveellison/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from IPython.kernel.zmq import kernelapp as app


In [10]:
sums = test.iloc[:,1:].sum()

In [11]:
values = pandas.Series(["Afghanistan"], ["Country Name"]).append(sums)

In [12]:
test_df = pandas.DataFrame(values)

In [13]:
test_df.transpose()

Country Name     2000     2001     2002    2003     2004    2005    2006  \
0  Afghanistan  1051112  1226098  3376479  912292  1066779  911679  527710   

     2007    2008    2009     2010     2011     2012    2013  
0  535632  515659  361985  1318019  1548374  1499351  985191

In [14]:
psq_tms_clean = pandas.read_csv("data/PSQ_TMS_filtered.csv")

In [15]:
gdp_info_raw = pandas.read_csv("data/world_bank_gdp/GDP_2011-2015.csv",skiprows=4)

In [16]:
gdp_clean = pandas.read_csv("data/world_bank_gdp/GDP_filtered.csv")

In [17]:
pov_raw = pandas.read_csv("data/world_bank_poverty/Poverty_raw.csv", skiprows=4)

In [18]:
pov_clean = pandas.read_csv("data/world_bank_poverty/Poverty_filtered.csv")

In [19]:
joined_data = pandas.merge(psq_tms_clean[["2013", "Country Name"]], fsi, on="Country Name")

In [20]:
finance_data = pandas.read_csv("data/financial_data.csv")

In [21]:
commodity_data = pandas.read_csv("data/commodities_filtered.csv")

In [22]:
finance_data_filtered = finance_data[["Country", "WEO Subject Code"] +[str(x) for x in range(2000, 2014)]]

In [23]:
finance_data_filtered.replace("n/a", numpy.nan, inplace=True)

/Users/steveellison/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [24]:
finance_data_filtered = finance_data_filtered[finance_data["WEO Subject Code"] == "NGDPD"]

In [25]:
finance_data_filtered.drop("WEO Subject Code", axis=1, inplace=True)

In [26]:
finance_data_filtered.rename(columns={str(col): "GDP (Billions of USD), " + str(col) for col in range(2000, 2014)}, inplace=True)

In [27]:
finance_data_filtered.rename(columns={"Country": "Country Name"}, inplace=True)

In [28]:
joined_data = pandas.merge(joined_data, finance_data_filtered, on="Country Name")

In [29]:
joined_data.rename(columns={"2013" : "Total Refugee Count, 2013"}, inplace=True)

In [30]:
joined_data = joined_data.applymap(lambda x: str(x).replace(",",""))

In [31]:
np_joined = joined_data.drop(["Country Name"], axis=1).as_matrix().astype("float64")
np_joined = np_joined[~numpy.isnan(np_joined).any(axis=1)]

In [32]:
from sklearn.cross_validation import train_test_split
from sklearn.svm import LinearSVR

from sklearn import metrics

In [33]:
target = np_joined[:,0]
features = np_joined[:,1:]

ftrain, ftest, ttrain, ttest = train_test_split(features, target, test_size=0.2, random_state=41234)

In [34]:
linear_svr = LinearSVR(loss='epsilon_insensitive', epsilon=0)

In [35]:
linear_svr.fit(ftrain, ttrain)
preds_svr = linear_svr.predict(ftest)
print numpy.sqrt(metrics.mean_squared_error(ttest, preds_svr))
print metrics.r2_score(ttest, preds_svr)

261220.844675
-0.0467511016811


In [36]:
metadata = pandas.read_csv("data/cpia/CPIA-Series.csv")
metadata[0:5]

Series Code                                 Topic  \
0  IQ.CPA.HRES.XQ  Public Sector: Policy & institutions   
1  IQ.CPA.BREG.XQ  Public Sector: Policy & institutions   
2  IQ.CPA.DEBT.XQ  Public Sector: Policy & institutions   
3  IQ.CPA.ECON.XQ  Public Sector: Policy & institutions   
4  IQ.CPA.REVN.XQ  Public Sector: Policy & institutions   

                                      Indicator Name  \
0  CPIA building human resources rating (1=low to...   
1  CPIA business regulatory environment rating (1...   
2          CPIA debt policy rating (1=low to 6=high)   
3  CPIA economic management cluster average (1=lo...   
4  CPIA efficiency of revenue mobilization rating...   

                                     Long definition Periodicity  \
0  Building human resources assesses the national...      Annual   
1  Business regulatory environment assesses the e...      Annual   
2  Debt policy assesses whether the debt manageme...      Annual   
3  The economic management cluster includes macro...      Annual   
4  Efficiency of revenue mobilization assesses th...      Annual   

   Aggregation method                         Limitations and exceptions  \
0  Unweighted average  The CPIA exercise is intended to capture the q...   
1  Unweighted average  The CPIA exercise is intended to capture the q...   
2  Unweighted average  The CPIA exercise is intended to capture the q...   
3  Unweighted average  The CPIA exercise is intended to capture the q...   
4  Unweighted average  The CPIA exercise is intended to capture the q...   

                                              Source  \
0  World Bank Group, CPIA database (http://www.wo...   
1  World Bank Group, CPIA database (http://www.wo...   
2  World Bank Group, CPIA database (http://www.wo...   
3  World Bank Group, CPIA database (http://www.wo...   
4  World Bank Group, CPIA database (http://www.wo...   

                 Statistical concept and methodology  \
0  All criteria within each cluster receive equal...   
1  All criteria within each cluster receive equal...   
2  All criteria within each cluster receive equal...   
3  All criteria within each cluster receive equal...   
4  All criteria within each cluster receive equal...   

                               Development relevance  
0  The International Development Association (IDA...  
1  The International Development Association (IDA...  
2  The International Development Association (IDA...  
3  The International Development Association (IDA...  
4  The International Development Association (IDA...

In [37]:
series_codes = metadata["Series Code"]

In [38]:
data = pandas.read_csv("data/cpia/CPIA-Data.csv")
print data.shape
data[numpy.isnan(data["2006"])].shape

(1995, 14)


(150, 14)

In [39]:
import cleanup_cpia as cpia

cpia.cleanup_cpia()

cleanup_cpia.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  axis=1, inplace=True)
/Users/steveellison/anaconda/lib/python2.7/site-packages/pandas/core/frame.py:2524: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)


In [40]:
cpia_clean = pandas.read_csv("data/cpia/CPIA-Data_clean.csv")

In [41]:
cpia_clean[0:5]

Country Name  IQ.CPA.HRES.XQ, 2005  IQ.CPA.HRES.XQ, 2006  \
0  Afghanistan                   NaN                     3   
1  Afghanistan                   NaN                     3   
2  Afghanistan                   NaN                     3   
3  Afghanistan                   NaN                     3   
4  Afghanistan                   NaN                     3   

   IQ.CPA.HRES.XQ, 2007  IQ.CPA.HRES.XQ, 2008  IQ.CPA.HRES.XQ, 2009  \
0                     3                     3                     3   
1                     3                     3                     3   
2                     3                     3                     3   
3                     3                     3                     3   
4                     3                     3                     3   

   IQ.CPA.HRES.XQ, 2010  IQ.CPA.HRES.XQ, 2011  IQ.CPA.HRES.XQ, 2012  \
0                     3                   3.5                   3.5   
1                     3                   3.5                   3.5   
2                     3                   3.5                   3.5   
3                     3                   3.5                   3.5   
4                     3                   3.5                   3.5   

   IQ.CPA.HRES.XQ, 2013          ...           IQ.CPA.IRAI.XQ, 2005  \
0                   3.5          ...                            NaN   
1                   3.5          ...                            NaN   
2                   3.5          ...                            NaN   
3                   3.5          ...                            NaN   
4                   3.5          ...                            NaN   

   IQ.CPA.IRAI.XQ, 2006  IQ.CPA.IRAI.XQ, 2007  IQ.CPA.IRAI.XQ, 2008  \
0              2.608333                   2.5                   2.6   
1              2.608333                   2.5                   2.6   
2              2.608333                   2.5                   2.6   
3              2.608333                   2.5                   2.6   
4              2.608333                   2.5                   2.6   

   IQ.CPA.IRAI.XQ, 2009  IQ.CPA.IRAI.XQ, 2010  IQ.CPA.IRAI.XQ, 2011  \
0                  2.75                 2.625                 2.675   
1                  2.75                 2.625                 2.675   
2                  2.75                 2.625                 2.675   
3                  2.75                 2.625                 2.675   
4                  2.75                 2.625                 2.675   

   IQ.CPA.IRAI.XQ, 2012  IQ.CPA.IRAI.XQ, 2013  IQ.CPA.IRAI.XQ, 2014  
0                 2.675                  2.65                  2.65  
1                 2.675                  2.65                  2.65  
2                 2.675                  2.65                  2.65  
3                 2.675                  2.65                  2.65  
4                 2.675                  2.65                  2.65  

[5 rows x 211 columns]

In [42]:
target = np_joined[:,0]

In [43]:
joined_data

Total Refugee Count, 2013              Country Name  \
0                   985191.0               Afghanistan   
1                    95921.0                   Algeria   
2                    45462.0                    Angola   
3                     4164.0                 Argentina   
4                    47878.0                 Australia   
5                   614260.0                Azerbaijan   
6                   231145.0                Bangladesh   
7                     7380.0                   Belarus   
8                    39477.0                   Belgium   
9                      291.0                     Benin   
10                  163737.0    Bosnia and Herzegovina   
11                    2983.0                  Botswana   
12                   22029.0                    Brazil   
13                    8784.0                  Bulgaria   
14                   29999.0              Burkina Faso   
15                  134345.0                   Burundi   
16                  123047.0                  Cameroon   
17                  911369.0  Central African Republic   
18                  454934.0                      Chad   
19                  301394.0                     China   
20                 5368403.0                  Colombia   
21                   21110.0                Costa Rica   
22                   18966.0                   Denmark   
23                  211533.0        Dominican Republic   
24                  135467.0                   Ecuador   
25                  253183.0                     Egypt   
26                      37.0               El Salvador   
27                       nan         Equatorial Guinea   
28                    3230.0                   Eritrea   
29                  435867.0                  Ethiopia   
..                       ...                       ...   
49                  260479.0                  Malaysia   
50                   93576.0                Mauritania   
51                    3094.0                    Mexico   
52                    4911.0                   Morocco   
53                   15099.0                Mozambique   
54                 1212388.0                   Myanmar   
55                   46950.0                     Nepal   
56                    2496.0                   Nigeria   
57                 2460014.0                  Pakistan   
58                     132.0                  Paraguay   
59                    1593.0                      Peru   
60                  335285.0               Philippines   
61                   29295.0                    Poland   
62                   81461.0                    Rwanda   
63                   70645.0              Saudi Arabia   
64                    2852.0              Sierra Leone   
65                 2083609.0                     Sudan   
66                    5674.0                Tajikistan   
67                  647570.0                  Thailand   
68                   21132.0                      Togo   
69                    1056.0                   Tunisia   
70                  663416.0                    Turkey   
71                    8360.0              Turkmenistan   
72                  294744.0                    Uganda   
73                   41618.0                   Ukraine   
74                  149186.0            United Kingdom   
75                     138.0                Uzbekistan   
76                  649126.0                     Yemen   
77                   52981.0                    Zambia   
78                   67082.0                  Zimbabwe   

   Demographic Pressures 2006 External Intervention 2006  \
0                         7.9                       10.0   
1                         6.0                        5.8   
2                         8.0                        7.6   
3                         3.0                        3.0   
4                         2.5                        1.0   
5                         6.0                 

In [44]:
from sklearn.cross_validation import train_test_split
from sklearn.svm import LinearSVR

from sklearn import metrics

In [54]:
labels = np_joined[:,0]
features = np_joined[:,1:]

from sklearn.cross_validation import train_test_split
ftrain, ftest, ltrain, ltest = train_test_split(features, labels, test_size=0.2, random_state=19890223)

In [75]:
from sklearn import linear_model

lossParam = ["hinge", "log", "modified_huber", "squared_hinge", "perceptron", "squared_loss", "huber", "epsilon_insensitive"]
penaltyParam = ["none", "l2", "l1", "elasticnet"]
matrixError = [[0 for x in range(len(penaltyParam))] for y in range(len(lossParam))] 
minError = float("inf")
minI = 0;
minJ = 0;
minR2 = float("inf")
minI2 = 0;
minj2 = 0;
matrixR2 = [[0 for x in range(len(penaltyParam))] for y in range(len(lossParam))] 

for k in range(0, 3):
    for i in range(0, len(lossParam)):
        for j in range(0, len(penaltyParam)):
            sgd = linear_model.SGDClassifier(learning_rate='constant', loss=lossParam[i], eta0=0.01, n_iter=10, penalty=penaltyParam[j], alpha=0.001)
            sgd.fit(ftrain,ltrain)
            prediction = sgd.predict(ftest)        
            matrixError[i][j] = (numpy.sqrt(metrics.mean_squared_error(ltest, prediction)))
            if matrixError[i][j] < minError:
                minError = matrixError[i][j]
                minI = i;
                minJ = j;
            matrixR2[i][j] = metrics.r2_score(ltest, prediction)
            if matrixR2[i][k] < minR2:
                minI2 = i;
                minJ2 = j;
                minR2 = matrixR2[i][j]
                
print "loss: " + lossParam[minI] + ", penalty: " + penaltyParam[minJ]
print matrixError[minI][minJ]            

print "loss: " + lossParam[minI2] + ", penalty: " + penaltyParam[minJ2]
print matrixR2[minI2][minJ2]


loss: modified_huber, penalty: elasticnet
179310.811869
loss: huber, penalty: l1
-447.176471798


In [81]:
from sklearn import tree
dt = tree.DecisionTreeClassifier(max_depth=6)
dt.fit(ftrain, ltrain)
prediction = dt.predict(ftest)
err = numpy.sqrt(metrics.mean_squared_error(ltest, prediction))
r2 = metrics.r2_score(ltest, prediction)

print "basic decision tree:"
print "error: "  
print err 
print " r2: " 
print r2

from sklearn import ensemble
bagged_dt = ensemble.BaggingClassifier(dt, n_estimators=5)

model_predictions = []
model_names = []

# Decision Tree
for i in [10,20,2,3,5]:
    dt = tree.DecisionTreeClassifier(max_depth=i)
    dt.fit(ftrain, ltrain)
    model_predictions.append(dt.predict_proba(ftest)[:,1])
    model_names.append('dt_' + str(i))
    
n_estimators=10

# Bagging + DT
for i in [5]:
    bg_dt_b = tree.DecisionTreeClassifier(max_depth=i)
    bg_dt = ensemble.BaggingClassifier(bg_dt_b, n_estimators=n_estimators, random_state=42)
    bg_dt.fit(ftrain, ltrain)
    model_predictions.append(bg_dt.predict_proba(ftest)[:,1])
    model_names.append('bagging_' + str(i) + '+dt')

import sklearn.metrics as ms
for i in range(len(model_predictions)):
    print model_names[i]
    print ms.roc_auc_score(ltest, model_predictions[i])



basic decision tree:
error: 
279004.799194
 r2: 
-0.640053695083
dt_10


ValueError: multiclass format is not supported

In [82]:
model_predictions

[array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.]),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.]),
 array([ 0.03571429,  0.        ,  0.03571429,  0.        ,  0.03571429,
         0.        ,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.        ,  0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.        ]),
 array([ 0.04,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.04,  0.  ,  0.04,
         0.  ,  0.  ,  0.04,  0.  ,  0.  ,  0.  ,  0.  ]),
 array([ 0.05,  0.  ,  0.  ,  0.05,  0.  ,  0.05,  0.05,  0.  ,  0.05,
         0.  ,  0.  ,  0.05,  0.  ,  0.  ,  0.05,  0.05]),
 array([ 0.0228261 ,  0.        ,  0.02033693,  0.02509883,  0.01371857,
         0.02509883,  0.02509883,  0.02509883,  0.02509883,  0.01852453,
         0.02259883,  0.02509883,  0.01848047,  0.01371432,  0.02033693,
         0.02292492])]